name: "Trending Repo Weekly"
description: "Fetch hot and new repos weekly"
author: "SolaTyolo<solat.yolo@gmail.com>"

branding:
  icon: 'cloud'
  color: 'purple'

inputs:
  lang: # change this
    required: true
    description: "Lang that need to fetch"
    default: "go"

runs:
  using: "node12"
  main: "dist/index.js"
